@echo off
echo Starting Freelance Marketplace Client...
cd /d "c:\Users\PC\freelance-marketplace\client"
echo Building CSS...
call npm run css:build
echo Starting React development server...
set BROWSER=none
call npm start
